JFLAGS = -g 
JC = javac

default: Home.class GroupManagement.class UserManagement.class AddUserToGroup.class CreateGroup.class EditImage.class ViewImage.class ViewUserImages.class UploadImage.class UploadImagesFromDir.class Login.class Register.class Search.class DataAnalysis.class RemoveImage.class GetThumbnailImage.class GetFullImage.class Filter.class SQLQueries.class DBConnection.class

Home.class: WEB-INF/classes/main/web/Home.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/Home.java

GroupManagement.class: WEB-INF/classes/main/web/GroupManagement.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/GroupManagement.java

UserManagement.class: WEB-INF/classes/main/web/UserManagement.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/UserManagement.java

ViewImage.class: WEB-INF/classes/main/web/ViewImage.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/ViewImage.java

RemoveImage.class: WEB-INF/classes/main/web/RemoveImage.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/RemoveImage.java

AddUserToGroup.class: WEB-INF/classes/main/web/AddUserToGroup.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/AddUserToGroup.java

CreateGroup.class: WEB-INF/classes/main/web/CreateGroup.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/CreateGroup.java

ViewUserImages.class: WEB-INF/classes/main/web/ViewUserImages.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/ViewUserImages.java

EditImage.class: WEB-INF/classes/main/web/EditImage.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/EditImage.java

UploadImage.class: WEB-INF/classes/main/web/UploadImage.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/UploadImage.java

UploadImagesFromDir.class: WEB-INF/classes/main/web/UploadImagesFromDir.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/UploadImagesFromDir.java

Login.class: WEB-INF/classes/main/web/Login.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/Login.java

Register.class: WEB-INF/classes/main/web/Register.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/Register.java

Search.class: WEB-INF/classes/main/web/Search.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/Search.java

DataAnalysis.class: WEB-INF/classes/main/web/DataAnalysis.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/DataAnalysis.java

GetFullImage.class: WEB-INF/classes/main/resource/GetFullImage.java
	${JC} ${JFLAGS} WEB-INF/classes/main/resource/GetFullImage.java

GetThumbnailImage.class: WEB-INF/classes/main/resource/GetThumbnailImage.java
	${JC} ${JFLAGS} WEB-INF/classes/main/resource/GetThumbnailImage.java

Filter.class: WEB-INF/classes/main/util/Filter.java
	${JC} ${JFLAGS} WEB-INF/classes/main/util/Filter.java

SQLQueries.class: WEB-INF/classes/main/util/SQLQueries.java
	${JC} ${JFLAGS} WEB-INF/classes/main/util/SQLQueries.java

DBConnection.class: WEB-INF/classes/main/util/DBConnection.java
	${JC} ${JFLAGS} WEB-INF/classes/main/util/DBConnection.java
