JFLAGS = -g
JC = javac

default: EditImage.class ViewImage.class ViewUserImages.class UploadImage.class Login.class Register.class Search.class

ViewImage.class: WEB-INF/classes/main/web/ViewImage.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/ViewImage.java

ViewUserImages.class: WEB-INF/classes/main/web/ViewUserImages.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/ViewUserImages.java

EditImage.class: WEB-INF/classes/main/web/EditImage.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/EditImage.java

UploadImage.class: WEB-INF/classes/main/web/UploadImage.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/UploadImage.java

UploadImagesFromDir.class: WEB-INF/classes/main/web/UploadImagesFromDir.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/UploadImagesFromDir.java

Login.class: WEB-INF/classes/main/web/Login.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/Login.java

Register.class: WEB-INF/classes/main/web/Register.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/Register.java

Search.class: WEB-INF/classes/main/web/Search.java
	${JC} ${JFLAGS} WEB-INF/classes/main/web/Search.java
